"""fix is_featured inside Ticket

Revision ID: 4a63d83f6069
Revises: d726e6a29528
Create Date: 2025-05-22 05:33:55.949679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a63d83f6069'
down_revision: Union[str, None] = 'd726e6a29528'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('is_featured', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'is_featured')
    # ### end Alembic commands ###
