"""add country_code to ticket

Revision ID: 52d1d6af6a58
Revises: 8d4a4e3a0d82
Create Date: 2025-05-25 15:05:03.310617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52d1d6af6a58'
down_revision: Union[str, None] = '8d4a4e3a0d82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('country_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'country_code')
    # ### end Alembic commands ###
