"""Add country_code to tickets

Revision ID: 66b2bd41741d
Revises: f179762e99b7
Create Date: 2025-05-25 19:33:03.825877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66b2bd41741d'
down_revision: Union[str, None] = 'f179762e99b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'country_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('country_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
