"""Add social_link and wallet_address to Ticket

Revision ID: a013f134e0e1
Revises: 4a63d83f6069
Create Date: 2025-05-25 05:17:46.380490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a013f134e0e1'
down_revision: Union[str, None] = '4a63d83f6069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('social_link', sa.String(), nullable=True))
    op.add_column('tickets', sa.Column('wallet_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'wallet_address')
    op.drop_column('tickets', 'social_link')
    # ### end Alembic commands ###
